// const pokemonsGenerator = require('./pokemonsGenerator')
// const Pokemon = require('./Pokemon').Pokemon
// debugger
// const scyther1 = pokemonsGenerator.makePokemon("scyther",25)
// const scyther2 = pokemonsGenerator.makePokemon("hitmonlee",25)
// const scyther3 = pokemonsGenerator.makePokemon("bulbasaur",25)
// const scyther4 = pokemonsGenerator.makePokemon("caterpie",25)
// const scyther5 = pokemonsGenerator.makePokemon("charmander",25)
// const scyther6 = pokemonsGenerator.makePokemon("eevee",25)
// const scyther7 = pokemonsGenerator.makePokemon("eknas",25)
// const scyther8 = pokemonsGenerator.makePokemon("geodude",25)
// const scyther9 = pokemonsGenerator.makePokemon("metapod",25)
// const scyther10 = pokemonsGenerator.makePokemon("pidgey",25)
// const scyther11 = pokemonsGenerator.makePokemon("pikachu",25)
// const scyther12 = pokemonsGenerator.makePokemon("ponyta",25)
// const scyther13 = pokemonsGenerator.makePokemon("psyduck",25)
// const scyther14 = pokemonsGenerator.makePokemon("raticate",25)
// const scyther15 = pokemonsGenerator.makePokemon("rattata",25)
// const scyther16 = pokemonsGenerator.makePokemon("spearow",25)
// const scyther17 = pokemonsGenerator.makePokemon("squirtle",25)
// const scyther18 = pokemonsGenerator.makePokemon("voltorb",25)
// const scyther19 = pokemonsGenerator.makePokemon("weedle",25)
// const scyther20 = pokemonsGenerator.makePokemon("vulpix",25)


// console.log('scyther1:', scyther1)
// console.log('scyther2:', scyther2)
// console.log('scyther3:', scyther3)
// console.log('scyther1:', scyther4)
// console.log('scyther1:', scyther5)
// console.log('scyther1:', scyther6)
// console.log('scyther1:', scyther7)
// console.log('scyther1:', scyther8)
// console.log('scyther1:', scyther9)
// console.log('scyther1:', scyther10)
// console.log('scyther1:', scyther11)
// console.log('scyther1:', scyther12)
// console.log('scyther1:', scyther13)
// console.log('scyther1:', scyther14)
// console.log('scyther1:', scyther15)
// console.log('scyther1:', scyther16)
// console.log('scyther1:', scyther17)
// console.log('scyther1:', scyther18)
// console.log('scyther1:', scyther19)
// console.log('scyther1:', scyther20)

